"""remove preference table

Revision ID: 019c8fe0c55c
Revises: 997ea69ffc87
Create Date: 2025-11-11 03:17:15.302563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '019c8fe0c55c'
down_revision = '997ea69ffc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('metric_system', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('light_dark_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reminder_frequency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_view', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_goal_priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_notification_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight_unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance_unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('theme_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification_sound', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('show_tutorials', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shortcut_keys_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('voice_assistant', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='preference_pkey')
    )
    # ### end Alembic commands ###
