"""add mindfulness tables

Revision ID: 024bc6b31dae
Revises: 019c8fe0c55c
Create Date: 2025-11-11 19:12:32.137932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '024bc6b31dae'
down_revision = '019c8fe0c55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LOW', 'MEDIUM', 'HIGH', name='reminderfrequency').create(op.get_bind())
    sa.Enum('BOX_4_4_4_4', 'RELAX_4_7_8', 'EQUAL_5_5', 'BALANCED_4_4', 'ENERGIZE_2_1', 'CUSTOM', 'WIM_HOF', name='breathingpatterntype').create(op.get_bind())
    sa.Enum('BREATHING', 'MEDITATION', 'REFLECTION', 'BIAS_AWARENESS', 'GROUNDING', 'BODY_SCAN', 'CUSTOM', name='exercisecategory').create(op.get_bind())
    sa.Enum('BREATHING', 'BODY_SCAN', 'FOCUSED', 'LOVING_KINDNESS', 'OPEN_AWARENESS', 'GUIDED', 'CUSTOM', name='meditationsessiontype').create(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='energylevel').create(op.get_bind())
    sa.Enum('GREAT', 'GOOD', 'NEUTRAL', 'LOW', 'POOR', name='moodtype').create(op.get_bind())
    op.create_table('cognitive_bias_logs',
    sa.Column('bias_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('situation', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('alternative_thinking', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_bias_logs_user_id'), 'cognitive_bias_logs', ['user_id'], unique=False)
    op.create_table('meditation_sessions',
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('session_type', postgresql.ENUM('BREATHING', 'BODY_SCAN', 'FOCUSED', 'LOVING_KINDNESS', 'OPEN_AWARENESS', 'GUIDED', 'CUSTOM', name='meditationsessiontype', create_type=False), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meditation_sessions_user_id'), 'meditation_sessions', ['user_id'], unique=False)
    op.create_table('mindfulness_exercises',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('category', postgresql.ENUM('BREATHING', 'MEDITATION', 'REFLECTION', 'BIAS_AWARENESS', 'GROUNDING', 'BODY_SCAN', 'CUSTOM', name='exercisecategory', create_type=False), nullable=False),
    sa.Column('technique', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('breathing_pattern', postgresql.ENUM('BOX_4_4_4_4', 'RELAX_4_7_8', 'EQUAL_5_5', 'BALANCED_4_4', 'ENERGIZE_2_1', 'CUSTOM', 'WIM_HOF', name='breathingpatterntype', create_type=False), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('custom_breathing_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('times_completed', sa.Integer(), nullable=False),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindfulness_exercises_is_preset'), 'mindfulness_exercises', ['is_preset'], unique=False)
    op.create_index(op.f('ix_mindfulness_exercises_user_id'), 'mindfulness_exercises', ['user_id'], unique=False)
    op.create_table('mindfulness_reminders',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('trigger_value', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('exercise_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('exercise_params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindfulness_reminders_user_id'), 'mindfulness_reminders', ['user_id'], unique=False)
    op.create_table('mindfulness_settings',
    sa.Column('daily_reflection_time', sa.Time(), nullable=True),
    sa.Column('reminder_frequency', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='reminderfrequency', create_type=False), nullable=False),
    sa.Column('preferred_meditation_duration', sa.Integer(), nullable=False),
    sa.Column('preferred_breathing_pattern', postgresql.ENUM('BOX_4_4_4_4', 'RELAX_4_7_8', 'EQUAL_5_5', 'BALANCED_4_4', 'ENERGIZE_2_1', 'CUSTOM', 'WIM_HOF', name='breathingpatterntype', create_type=False), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('integration_points', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindfulness_settings_user_id'), 'mindfulness_settings', ['user_id'], unique=True)
    op.create_table('mood_entries',
    sa.Column('mood', postgresql.ENUM('GREAT', 'GOOD', 'NEUTRAL', 'LOW', 'POOR', name='moodtype', create_type=False), nullable=False),
    sa.Column('energy', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='energylevel', create_type=False), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('productivity_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entries_user_id'), 'mood_entries', ['user_id'], unique=False)
    op.create_table('reflection_entries',
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_entries_user_id'), 'reflection_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_entries_user_id'), table_name='reflection_entries')
    op.drop_table('reflection_entries')
    op.drop_index(op.f('ix_mood_entries_user_id'), table_name='mood_entries')
    op.drop_table('mood_entries')
    op.drop_index(op.f('ix_mindfulness_settings_user_id'), table_name='mindfulness_settings')
    op.drop_table('mindfulness_settings')
    op.drop_index(op.f('ix_mindfulness_reminders_user_id'), table_name='mindfulness_reminders')
    op.drop_table('mindfulness_reminders')
    op.drop_index(op.f('ix_mindfulness_exercises_user_id'), table_name='mindfulness_exercises')
    op.drop_index(op.f('ix_mindfulness_exercises_is_preset'), table_name='mindfulness_exercises')
    op.drop_table('mindfulness_exercises')
    op.drop_index(op.f('ix_meditation_sessions_user_id'), table_name='meditation_sessions')
    op.drop_table('meditation_sessions')
    op.drop_index(op.f('ix_cognitive_bias_logs_user_id'), table_name='cognitive_bias_logs')
    op.drop_table('cognitive_bias_logs')
    sa.Enum('GREAT', 'GOOD', 'NEUTRAL', 'LOW', 'POOR', name='moodtype').drop(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='energylevel').drop(op.get_bind())
    sa.Enum('BREATHING', 'BODY_SCAN', 'FOCUSED', 'LOVING_KINDNESS', 'OPEN_AWARENESS', 'GUIDED', 'CUSTOM', name='meditationsessiontype').drop(op.get_bind())
    sa.Enum('BREATHING', 'MEDITATION', 'REFLECTION', 'BIAS_AWARENESS', 'GROUNDING', 'BODY_SCAN', 'CUSTOM', name='exercisecategory').drop(op.get_bind())
    sa.Enum('BOX_4_4_4_4', 'RELAX_4_7_8', 'EQUAL_5_5', 'BALANCED_4_4', 'ENERGIZE_2_1', 'CUSTOM', 'WIM_HOF', name='breathingpatterntype').drop(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', name='reminderfrequency').drop(op.get_bind())
    # ### end Alembic commands ###
