"""add daily review reminder preferences

Revision ID: 07f471bb6637
Revises: cc9dd806f4b6
Create Date: 2025-10-12 14:33:25.203247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '07f471bb6637'
down_revision = 'cc9dd806f4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_reminder', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('WHEEL_OF_LIFE_REMINDER', 'WHEEL_OF_LIFE_COMPLETED', 'WHEEL_OF_LIFE_INSIGHTS_AVAILABLE', 'WHEEL_OF_LIFE_SIGNIFICANT_CHANGE', 'HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype'),
               existing_nullable=False,
               postgresql_using='event_type::eventtype')
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='remindertype',
        new_values=['HABIT', 'WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'GOAL_DEADLINE', 'GOAL_MILESTONE', 'JOURNAL_PROMPT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', 'DAILY_REVIEW', 'USER_CUSTOM'],
        affected_columns=[TableReference(table_schema='public', table_name='scheduled_reminder', column_name='reminder_type')],
        enum_values_to_rename=[],
    )
    # 1️⃣ Add column as nullable with a default server value
    op.add_column('usernotificationpreference', sa.Column(
        'daily_review_enabled',
        sa.Boolean(),
        nullable=True,
        server_default=sa.text('true')
    ))
    op.add_column('usernotificationpreference', sa.Column(
        'daily_review_time_preference',
        sa.String(),
        nullable=True,
        server_default=sa.text("'auto'")
    ))
    op.add_column('usernotificationpreference', sa.Column(
        'daily_review_custom_time',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=True
    ))
    op.add_column('usernotificationpreference', sa.Column(
        'daily_review_completion_threshold',
        sa.Float(),
        nullable=True,
        server_default=sa.text('0.7')
    ))

    # 2️⃣ Update existing rows to use the defaults (optional if using server_default)
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE usernotificationpreference
        SET daily_review_enabled = true,
            daily_review_time_preference = 'auto',
            daily_review_completion_threshold = 0.7
        WHERE daily_review_enabled IS NULL
    """))

    # 3️⃣ Make the columns non-nullable
    op.alter_column('usernotificationpreference', 'daily_review_enabled', nullable=False)
    op.alter_column('usernotificationpreference', 'daily_review_time_preference', nullable=False)
    op.alter_column('usernotificationpreference', 'daily_review_completion_threshold', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='remindertype',
        new_values=['HABIT', 'WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'GOAL_DEADLINE', 'GOAL_MILESTONE', 'JOURNAL_PROMPT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', 'USER_CUSTOM'],
        affected_columns=[TableReference(table_schema='public', table_name='scheduled_reminder', column_name='reminder_type')],
        enum_values_to_rename=[],
    )
    op.drop_column('usernotificationpreference', 'daily_review_completion_threshold')
    op.drop_column('usernotificationpreference', 'daily_review_custom_time')
    op.drop_column('usernotificationpreference', 'daily_review_time_preference')
    op.drop_column('usernotificationpreference', 'daily_review_enabled')
    op.alter_column('scheduled_reminder', 'event_type',
               existing_type=sa.Enum('WHEEL_OF_LIFE_REMINDER', 'WHEEL_OF_LIFE_COMPLETED', 'WHEEL_OF_LIFE_INSIGHTS_AVAILABLE', 'WHEEL_OF_LIFE_SIGNIFICANT_CHANGE', 'HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
