"""remove version unique constraint

Revision ID: 0df5b62be457
Revises: bd82c79c610c
Create Date: 2025-10-30 01:48:35.498001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0df5b62be457'
down_revision = 'bd82c79c610c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indepthassessmentversion_version_key', 'indepthassessmentversion', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('indepthassessmentversion_version_key', 'indepthassessmentversion', ['version'])
    # ### end Alembic commands ###
