"""wheel of life change in_depth in favor of detailed assessments type

Revision ID: 1f70ca0dade4
Revises: 8ee8bc1dafaf
Create Date: 2025-10-31 18:36:58.948862

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '1f70ca0dade4'
down_revision = '8ee8bc1dafaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='assessmenttype',
        new_values=['QUICK', 'DETAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='wheelassessment', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='assessmenttype',
        new_values=['QUICK', 'IN_DEPTH'],
        affected_columns=[TableReference(table_schema='public', table_name='wheelassessment', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
