"""add wheel of life enums

Revision ID: 2207e00bfa72
Revises: b1a8f2442667
Create Date: 2025-09-19 15:06:49.662848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '2207e00bfa72'
down_revision = 'b1a8f2442667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='eventtype',
        new_values=['WHEEL_OF_LIFE_REMINDER', 'WHEEL_OF_LIFE_COMPLETED', 'WHEEL_OF_LIFE_INSIGHTS_AVAILABLE', 'WHEEL_OF_LIFE_SIGNIFICANT_CHANGE', 'HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='event_type'), TableReference(table_schema='public', table_name='notificationrule', column_name='event_type'), TableReference(table_schema='public', table_name='notificationtemplate', column_name='event_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='eventtype',
        new_values=['HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='event_type'), TableReference(table_schema='public', table_name='notificationrule', column_name='event_type'), TableReference(table_schema='public', table_name='notificationtemplate', column_name='event_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
