"""add reset_hout_utc to user table

Revision ID: 254ef02e8b1e
Revises: d29eb07f778f
Create Date: 2025-10-23 17:13:02.237680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '254ef02e8b1e'
down_revision = 'd29eb07f778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default
    op.add_column('user', sa.Column('reset_hour_utc', sa.Integer(), nullable=False, server_default='0'))

    # Remove server_default after column is created (optional, keeps schema clean)
    op.alter_column('user', 'reset_hour_utc', server_default=None, default=0)

    # Create the index
    op.create_index(op.f('ix_user_reset_hour_utc'), 'user', ['reset_hour_utc'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_hour_utc'), table_name='user')
    op.drop_column('user', 'reset_hour_utc')
    # ### end Alembic commands ###
