"""add color_class to lifearea

Revision ID: 3d5fab11a7ee
Revises: 1f70ca0dade4
Create Date: 2025-10-31 20:35:36.701439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d5fab11a7ee'
down_revision = '1f70ca0dade4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifearea', sa.Column('color_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifearea', 'color_class')
    # ### end Alembic commands ###
