"""lifeareas upgreade

Revision ID: 4a174255c9d3
Revises: b84c110acb82
Create Date: 2025-08-22 17:39:07.282840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a174255c9d3'
down_revision = 'b84c110acb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel').create(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='evidencelevel').create(op.get_bind())
    op.add_column('habit', sa.Column('evidence_level', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='evidencelevel', create_type=False), nullable=True))
    op.add_column('habit', sa.Column('difficulty', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel', create_type=False), nullable=True))
    op.add_column('habit', sa.Column('recommended_by', sa.JSON(), nullable=True))
    op.add_column('habit', sa.Column('benefits', sa.JSON(), nullable=True))
    op.add_column('habit', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('habit', sa.Column('goal_description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('habit', sa.Column('stacked_with_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_index('ix_habit_difficulty', 'habit', ['difficulty'], unique=False)
    op.create_index('ix_habit_evidence_level', 'habit', ['evidence_level'], unique=False)
    op.create_index('ix_habit_is_active', 'habit', ['is_active'], unique=False)
    op.create_index('ix_habit_user_id', 'habit', ['user_id'], unique=False)
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='lifeareasenum',
        new_values=['HEALTH', 'CAREER', 'RELATIONSHIPS', 'PERSONAL_GROWTH', 'FINANCE', 'RECREATION', 'ENVIRONMENT', 'SPIRITUALITY', 'CONTRIBUTION'],
        affected_columns=[TableReference(table_schema='public', table_name='lifearea', column_name='name')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='lifeareasenum',
        new_values=['FRIENDS', 'RELATIONSHIPS', 'LOVE', 'MONEY', 'SPIRITUALITY', 'FUN', 'CAREER', 'HEALTH', 'FAMILY', 'GROWTH', 'FINANCE'],
        affected_columns=[TableReference(table_schema='public', table_name='lifearea', column_name='name')],
        enum_values_to_rename=[],
    )
    op.drop_index('ix_habit_user_id', table_name='habit')
    op.drop_index('ix_habit_is_active', table_name='habit')
    op.drop_index('ix_habit_evidence_level', table_name='habit')
    op.drop_index('ix_habit_difficulty', table_name='habit')
    op.drop_column('habit', 'stacked_with_name')
    op.drop_column('habit', 'goal_description')
    op.drop_column('habit', 'tags')
    op.drop_column('habit', 'benefits')
    op.drop_column('habit', 'recommended_by')
    op.drop_column('habit', 'difficulty')
    op.drop_column('habit', 'evidence_level')
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='evidencelevel').drop(op.get_bind())
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel').drop(op.get_bind())
    # ### end Alembic commands ###
