"""remove milestones from dreams

Revision ID: 5a7aef03395c
Revises: af7db6bb52f6
Create Date: 2025-11-04 22:39:34.065710

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a7aef03395c'
down_revision = 'af7db6bb52f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dream_milestone_dream_id', table_name='dream_milestone')
    op.drop_table('dream_milestone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_milestone',
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], name='dream_milestone_dream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dream_milestone_pkey')
    )
    op.create_index('ix_dream_milestone_dream_id', 'dream_milestone', ['dream_id'], unique=False)
    # ### end Alembic commands ###
