"""redos

Revision ID: 674d62189f40
Revises: 8a14d90aeaca
Create Date: 2025-08-01 21:09:36.709740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '674d62189f40'
down_revision = '8a14d90aeaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_completion', sa.Column('redo_progression', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_completion', 'redo_progression')
    # ### end Alembic commands ###
