"""clean habits table

Revision ID: 6fbfd9e5f624
Revises: 254ef02e8b1e
Create Date: 2025-10-24 03:43:38.973170

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6fbfd9e5f624'
down_revision = '254ef02e8b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'is_the_one_thing')
    op.drop_column('habit', 'hasFlexibility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('hasFlexibility', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('habit', sa.Column('is_the_one_thing', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
