"""add telegram_bot_token to user preferences

Revision ID: 796257334f7b
Revises: d4f21a123d4a
Create Date: 2025-09-26 15:40:22.443807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '796257334f7b'
down_revision = 'd4f21a123d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotificationpreference', sa.Column('telegram_bot_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('usernotificationpreference', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotificationpreference', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usernotificationpreference', 'telegram_bot_token')
    # ### end Alembic commands ###
