"""drop old wheel of life and assessments tables

Revision ID: 7b66b7b33d2c
Revises: d2e40a2cb0c6
Create Date: 2025-10-29 22:32:08.364520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b66b7b33d2c'
down_revision = 'd2e40a2cb0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessmentresult')
    op.drop_table('wheeloflifelifearealink')
    op.drop_table('assessmentquestion')
    op.drop_table('assessment')
    op.drop_table('wheeloflife')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheeloflife',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wheeloflife_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wheeloflife_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assessmentquestion',
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='assessmentquestion_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessmentquestion_pkey')
    )
    op.create_table('assessment',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notes_and_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lifearea_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], name='assessment_lifearea_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('wheeloflifelifearealink',
    sa.Column('wheeloflife_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lifearea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lifeArea_alias', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], name='wheeloflifelifearealink_lifearea_id_fkey'),
    sa.ForeignKeyConstraint(['wheeloflife_id'], ['wheeloflife.id'], name='wheeloflifelifearealink_wheeloflife_id_fkey'),
    sa.PrimaryKeyConstraint('wheeloflife_id', 'lifearea_id', name='wheeloflifelifearealink_pkey')
    )
    op.create_table('assessmentresult',
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes_and_remarks', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='assessmentresult_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='assessmentresult_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessmentresult_pkey')
    )
    # ### end Alembic commands ###
