"""lifearea add label

Revision ID: 8ee8bc1dafaf
Revises: 0df5b62be457
Create Date: 2025-10-31 00:44:34.780327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.sql import table, column
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision = '8ee8bc1dafaf'
down_revision = '0df5b62be457'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the column as nullable
    op.add_column('lifearea', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Step 2: Fill the labels based on the enum mapping
    label_mapping = {
        'HEALTH': 'Health',
        'CAREER': 'Career',
        'RELATIONSHIPS': 'Relationships',
        'PERSONAL_GROWTH': 'Personal growth',
        'FINANCE': 'Finance',
        'RECREATION': 'Recreation',
        'ENVIRONMENT': 'Environment',
        'SPIRITUALITY': 'Spirituality',
        'CONTRIBUTION': 'Contribution',
    }

    # Update each row with its corresponding label using raw SQL
    # Cast the enum to text for comparison
    for name, label in label_mapping.items():
        op.execute(
            f"UPDATE lifearea SET label = '{label}' WHERE name::text = '{name}'"
        )

    # Step 3: Make the column non-nullable
    op.alter_column('lifearea', 'label', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifearea', 'label')
    # ### end Alembic commands ###
