"""completion type E

Revision ID: 93d0fddc3d33
Revises: d568327b9150
Create Date: 2025-08-19 23:47:58.574801

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d0fddc3d33'
down_revision = 'd568327b9150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('scheduled', 'bonus', 'makeup', name='completiontype').create(op.get_bind())
    op.add_column('habit_completion', sa.Column('completion_type', postgresql.ENUM('scheduled', 'bonus', 'makeup', name='completiontype', create_type=False), nullable=True))
    op.drop_column('user', 'preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('habit_completion', 'completion_type')
    sa.Enum('scheduled', 'bonus', 'makeup', name='completiontype').drop(op.get_bind())
    # ### end Alembic commands ###
