"""remove dream habits and trackables; connect them with goals only

Revision ID: 950cecfef878
Revises: ad1e5a3f220e
Create Date: 2025-11-07 16:18:31.843543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '950cecfef878'
down_revision = 'ad1e5a3f220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_habit',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'habit_id')
    )
    op.create_table('goal_trackable',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('trackable_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'trackable_id')
    )
    op.drop_table('dream_trackable')
    op.drop_table('dream_habit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_habit',
    sa.Column('dream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('habit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], name='dream_habit_dream_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], name='dream_habit_habit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'habit_id', name='dream_habit_pkey')
    )
    op.create_table('dream_trackable',
    sa.Column('dream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trackable_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], name='dream_trackable_dream_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], name='dream_trackable_trackable_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'trackable_id', name='dream_trackable_pkey')
    )
    op.drop_table('goal_trackable')
    op.drop_table('goal_habit')
    # ### end Alembic commands ###
