"""UserDream to Dream

Revision ID: 997ea69ffc87
Revises: b9ad2bfcfa7c
Create Date: 2025-11-11 02:58:07.689203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '997ea69ffc87'
down_revision = 'b9ad2bfcfa7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_life_area_id', sa.Uuid(), nullable=False),
    sa.Column('why', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', 'NEXT', 'SOMEDAY', name='dreamstatus', create_type=False), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('achieved_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_life_area_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_user_id'), 'dream', ['user_id'], unique=False)
    op.drop_index('ix_user_dream_user_id', table_name='user_dream')
    op.drop_constraint('dream_goal_dream_id_fkey', 'dream_goal', type_='foreignkey')
    op.drop_table('user_dream')
    op.create_foreign_key(None, 'dream_goal', 'dream', ['dream_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dream_goal', type_='foreignkey')
    op.create_foreign_key('dream_goal_dream_id_fkey', 'dream_goal', 'user_dream', ['dream_id'], ['id'], ondelete='CASCADE')
    op.create_table('user_dream',
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_life_area_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('why', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', 'NEXT', 'SOMEDAY', name='dreamstatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('target_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('achieved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('paused_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['primary_life_area_id'], ['lifearea.id'], name='user_dream_primary_life_area_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_dream_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_dream_pkey')
    )
    op.create_index('ix_user_dream_user_id', 'user_dream', ['user_id'], unique=False)
    op.drop_index(op.f('ix_dream_user_id'), table_name='dream')
    op.drop_table('dream')
    # ### end Alembic commands ###
