"""update  wheel-of-life and assessments

Revision ID: 9fcb9376ddfe
Revises: 7b66b7b33d2c
Create Date: 2025-10-29 22:34:35.742595

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fcb9376ddfe'
down_revision = '7b66b7b33d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SCALE', 'MULTIPLE_CHOICE', 'TEXT', name='questiontype').create(op.get_bind())
    sa.Enum('QUICK', 'IN_DEPTH', name='assessmenttype').create(op.get_bind())
    op.create_table('indepthassessmentversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('life_area_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['life_area_id'], ['lifearea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessmentquestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_version_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('SCALE', 'MULTIPLE_CHOICE', 'TEXT', name='questiontype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_version_id'], ['indepthassessmentversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wheelassessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('QUICK', 'IN_DEPTH', name='assessmenttype', create_type=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areaassessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wheel_assessment_id', sa.Uuid(), nullable=False),
    sa.Column('life_area_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_quick', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['life_area_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['wheel_assessment_id'], ['wheelassessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessmentquestionoption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assessmentquestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useranswer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_value', sa.Float(), nullable=True),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessmentquestion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useransweroption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_answer_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['assessmentquestionoption.id'], ),
    sa.ForeignKeyConstraint(['user_answer_id'], ['useranswer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useransweroption')
    op.drop_table('useranswer')
    op.drop_table('assessmentquestionoption')
    op.drop_table('areaassessment')
    op.drop_table('wheelassessment')
    op.drop_table('assessmentquestion')
    op.drop_table('indepthassessmentversion')
    sa.Enum('QUICK', 'IN_DEPTH', name='assessmenttype').drop(op.get_bind())
    sa.Enum('SCALE', 'MULTIPLE_CHOICE', 'TEXT', name='questiontype').drop(op.get_bind())
    # ### end Alembic commands ###
