"""add notification categories

Revision ID: a33239682eb9
Revises: faf720132978
Create Date: 2025-09-25 15:43:03.515342

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a33239682eb9'
down_revision = 'faf720132978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotificationpreference', sa.Column('habit_reminders', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('streak_milestones', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('goal_updates', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('weekly_reports', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('achievements', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('system_updates', sa.Boolean(), nullable=False))
    op.add_column('usernotificationpreference', sa.Column('security_alerts', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotificationpreference', 'security_alerts')
    op.drop_column('usernotificationpreference', 'system_updates')
    op.drop_column('usernotificationpreference', 'achievements')
    op.drop_column('usernotificationpreference', 'weekly_reports')
    op.drop_column('usernotificationpreference', 'goal_updates')
    op.drop_column('usernotificationpreference', 'streak_milestones')
    op.drop_column('usernotificationpreference', 'habit_reminders')
    # ### end Alembic commands ###
