"""add values tables

Revision ID: abc123def456
Revises: faf720132978
Create Date: 2025-11-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'faf720132978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create corevalue table
    op.create_table('corevalue',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Create valueassessment table
    op.create_table('valueassessment',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('assessment_date', sa.DateTime(), nullable=False),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create valueassessmentresponse table
    op.create_table('valueassessmentresponse',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('value_assessment_id', sa.Uuid(), nullable=False),
        sa.Column('core_value_id', sa.Uuid(), nullable=False),
        sa.Column('importance_score', sa.Float(), nullable=False),
        sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['core_value_id'], ['corevalue.id'], ),
        sa.ForeignKeyConstraint(['value_assessment_id'], ['valueassessment.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Add indexes for better query performance
    op.create_index('ix_valueassessment_user_id', 'valueassessment', ['user_id'])
    op.create_index('ix_valueassessment_assessment_date', 'valueassessment', ['assessment_date'])
    op.create_index('ix_valueassessmentresponse_assessment_id', 'valueassessmentresponse', ['value_assessment_id'])
    op.create_index('ix_corevalue_is_active', 'corevalue', ['is_active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('ix_corevalue_is_active', table_name='corevalue')
    op.drop_index('ix_valueassessmentresponse_assessment_id', table_name='valueassessmentresponse')
    op.drop_index('ix_valueassessment_assessment_date', table_name='valueassessment')
    op.drop_index('ix_valueassessment_user_id', table_name='valueassessment')

    # Drop tables in reverse order (respecting foreign keys)
    op.drop_table('valueassessmentresponse')
    op.drop_table('valueassessment')
    op.drop_table('corevalue')

    # ### end Alembic commands ###
