"""add scheduled_chec_in

Revision ID: ad1e5a3f220e
Revises: b9cbb6f6ea3e
Create Date: 2025-11-06 03:45:35.529816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad1e5a3f220e'
down_revision = 'b9cbb6f6ea3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'BIANNUAL', 'ANNUAL', 'CUSTOM', name='checkinfrequency').create(op.get_bind())
    sa.Enum('WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', name='checkintype').create(op.get_bind())
    op.create_table('scheduled_check_in',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_in_type', postgresql.ENUM('WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', name='checkintype', create_type=False), nullable=False),
    sa.Column('next_check_in', sa.DateTime(), nullable=False),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('frequency', postgresql.ENUM('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'BIANNUAL', 'ANNUAL', 'CUSTOM', name='checkinfrequency', create_type=False), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('send_reminder', sa.Boolean(), nullable=False),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_check_ins', 'scheduled_check_in', ['user_id', 'is_active', 'next_check_in'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_due_check_ins', 'scheduled_check_in', ['next_check_in', 'is_active'], unique=False)
    op.create_index(op.f('ix_scheduled_check_in_check_in_type'), 'scheduled_check_in', ['check_in_type'], unique=False)
    op.create_index(op.f('ix_scheduled_check_in_next_check_in'), 'scheduled_check_in', ['next_check_in'], unique=False)
    op.create_index(op.f('ix_scheduled_check_in_user_id'), 'scheduled_check_in', ['user_id'], unique=False)
    op.create_index('ix_user_type', 'scheduled_check_in', ['user_id', 'check_in_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_type', table_name='scheduled_check_in')
    op.drop_index(op.f('ix_scheduled_check_in_user_id'), table_name='scheduled_check_in')
    op.drop_index(op.f('ix_scheduled_check_in_next_check_in'), table_name='scheduled_check_in')
    op.drop_index(op.f('ix_scheduled_check_in_check_in_type'), table_name='scheduled_check_in')
    op.drop_index('ix_due_check_ins', table_name='scheduled_check_in')
    op.drop_index('ix_active_check_ins', table_name='scheduled_check_in', postgresql_where='is_active = true')
    op.drop_table('scheduled_check_in')
    sa.Enum('WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', name='checkintype').drop(op.get_bind())
    sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'BIANNUAL', 'ANNUAL', 'CUSTOM', name='checkinfrequency').drop(op.get_bind())
    # ### end Alembic commands ###
