"""update  wheel-of-life and assessments: fix life_area

Revision ID: ad522a5c5ba7
Revises: 9fcb9376ddfe
Create Date: 2025-10-29 22:43:30.661718

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad522a5c5ba7'
down_revision = '9fcb9376ddfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areaassessment', sa.Column('lifearea_id', sa.Uuid(), nullable=False))
    op.drop_constraint('areaassessment_life_area_id_fkey', 'areaassessment', type_='foreignkey')
    op.create_foreign_key(None, 'areaassessment', 'lifearea', ['lifearea_id'], ['id'])
    op.drop_column('areaassessment', 'life_area_id')
    op.add_column('indepthassessmentversion', sa.Column('lifearea_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'indepthassessmentversion', ['version'])
    op.drop_constraint('indepthassessmentversion_life_area_id_fkey', 'indepthassessmentversion', type_='foreignkey')
    op.create_foreign_key(None, 'indepthassessmentversion', 'lifearea', ['lifearea_id'], ['id'])
    op.drop_column('indepthassessmentversion', 'life_area_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indepthassessmentversion', sa.Column('life_area_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'indepthassessmentversion', type_='foreignkey')
    op.create_foreign_key('indepthassessmentversion_life_area_id_fkey', 'indepthassessmentversion', 'lifearea', ['life_area_id'], ['id'])
    op.drop_constraint(None, 'indepthassessmentversion', type_='unique')
    op.drop_column('indepthassessmentversion', 'lifearea_id')
    op.add_column('areaassessment', sa.Column('life_area_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'areaassessment', type_='foreignkey')
    op.create_foreign_key('areaassessment_life_area_id_fkey', 'areaassessment', 'lifearea', ['life_area_id'], ['id'])
    op.drop_column('areaassessment', 'lifearea_id')
    # ### end Alembic commands ###
