"""add dreams

Revision ID: af7db6bb52f6
Revises: 77e6e7a9ae20
Create Date: 2025-11-04 18:54:57.384836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af7db6bb52f6'
down_revision = '77e6e7a9ae20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', name='dreamstatus').create(op.get_bind())
    op.create_table('user_dream',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_life_area_id', sa.Uuid(), nullable=False),
    sa.Column('why', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', name='dreamstatus', create_type=False), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('achieved_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_life_area_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dream_user_id'), 'user_dream', ['user_id'], unique=False)
    op.create_table('dream_goal',
    sa.Column('dream_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'goal_id')
    )
    op.create_table('dream_milestone',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dream_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_milestone_dream_id'), 'dream_milestone', ['dream_id'], unique=False)
    op.create_table('dream_habit',
    sa.Column('dream_id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'habit_id')
    )
    op.create_table('dream_trackable',
    sa.Column('dream_id', sa.Uuid(), nullable=False),
    sa.Column('trackable_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['user_dream.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dream_id', 'trackable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dream_trackable')
    op.drop_table('dream_habit')
    op.drop_index(op.f('ix_dream_milestone_dream_id'), table_name='dream_milestone')
    op.drop_table('dream_milestone')
    op.drop_table('dream_goal')
    op.drop_index(op.f('ix_user_dream_user_id'), table_name='user_dream')
    op.drop_table('user_dream')
    sa.Enum('ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', name='dreamstatus').drop(op.get_bind())
    # ### end Alembic commands ###
