"""unify notifications

Revision ID: b1a8f2442667
Revises: b7f3b488b163
Create Date: 2025-09-18 11:04:11.676556

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1a8f2442667'
down_revision = 'b7f3b488b163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'DISMISSED', 'FAILED', 'CANCELLED', 'EXPIRED', name='notificationstatus').create(op.get_bind())
    sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority').create(op.get_bind())
    sa.Enum('IN_APP', 'EMAIL', 'PUSH', 'SMS', 'WEBHOOK', 'DISCORD', 'SLACK', 'TEAMS', 'TELEGRAM', 'WHATSAPP', 'VOICE', 'DESKTOP', name='notificationchannel').create(op.get_bind())
    sa.Enum('HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype').create(op.get_bind())
    op.create_table('notificationrule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_type', postgresql.ENUM('HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype', create_type=False), nullable=False),
    sa.Column('user_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority', create_type=False), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_window', sa.Integer(), nullable=True),
    sa.Column('rate_limit_count', sa.Integer(), nullable=True),
    sa.Column('respect_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('respect_user_channel_prefs', sa.Boolean(), nullable=False),
    sa.Column('requires_opt_in', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificationtemplate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_type', postgresql.ENUM('HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype', create_type=False), nullable=False),
    sa.Column('channel', postgresql.ENUM('IN_APP', 'EMAIL', 'PUSH', 'SMS', 'WEBHOOK', 'DISCORD', 'SLACK', 'TEAMS', 'TELEGRAM', 'WHATSAPP', 'VOICE', 'DESKTOP', name='notificationchannel', create_type=False), nullable=False),
    sa.Column('subject_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_template', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype', create_type=False), nullable=False),
    sa.Column('channel', postgresql.ENUM('IN_APP', 'EMAIL', 'PUSH', 'SMS', 'WEBHOOK', 'DISCORD', 'SLACK', 'TEAMS', 'TELEGRAM', 'WHATSAPP', 'VOICE', 'DESKTOP', name='notificationchannel', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'DISMISSED', 'FAILED', 'CANCELLED', 'EXPIRED', name='notificationstatus', create_type=False), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_metadata', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['notificationrule.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notificationtemplate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernotificationpreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('teams_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('push_tokens', sa.JSON(), nullable=True),
    sa.Column('webhook_urls', sa.JSON(), nullable=True),
    sa.Column('discord_webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discord_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slack_webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slack_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teams_webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_preferences', sa.JSON(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quiet_hours_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weekend_notifications', sa.Boolean(), nullable=False),
    sa.Column('max_daily_notifications', sa.Integer(), nullable=False),
    sa.Column('max_hourly_notifications', sa.Integer(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernotificationpreference')
    op.drop_table('notification')
    op.drop_table('notificationtemplate')
    op.drop_table('notificationrule')
    sa.Enum('HABIT_REMINDER', 'HABIT_COMPLETED', 'HABIT_STREAK_MILESTONE', 'HABIT_OVERDUE', 'GOAL_REMINDER', 'GOAL_ACHIEVED', 'GOAL_DEADLINE_APPROACHING', 'GOAL_PROGRESS_UPDATE', 'JOURNAL_PROMPT', 'JOURNAL_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM_ANNOUNCEMENT', 'ACCOUNT_CREATED', 'PASSWORD_RESET', 'LOGIN_SUSPICIOUS', 'SUBSCRIPTION_EXPIRING', 'CHALLENGE_INVITATION', 'FRIEND_REQUEST', 'ACHIEVEMENT_SHARED', name='eventtype').drop(op.get_bind())
    sa.Enum('IN_APP', 'EMAIL', 'PUSH', 'SMS', 'WEBHOOK', 'DISCORD', 'SLACK', 'TEAMS', 'TELEGRAM', 'WHATSAPP', 'VOICE', 'DESKTOP', name='notificationchannel').drop(op.get_bind())
    sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'DISMISSED', 'FAILED', 'CANCELLED', 'EXPIRED', name='notificationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
