"""preferences upgrade

Revision ID: b4cf87a2a016
Revises: 35ccd2f7a729
Create Date: 2025-07-29 08:40:07.059952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4cf87a2a016'
down_revision = '35ccd2f7a729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('mobile_preferences', sa.JSON(), nullable=True))
    op.add_column('user_preferences', sa.Column('tablet_preferences', sa.JSON(), nullable=True))
    op.add_column('user_preferences', sa.Column('desktop_preferences', sa.JSON(), nullable=True))
    op.drop_column('user_preferences', 'device_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('device_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_preferences', 'desktop_preferences')
    op.drop_column('user_preferences', 'tablet_preferences')
    op.drop_column('user_preferences', 'mobile_preferences')
    # ### end Alembic commands ###
