"""user settings

Revision ID: b53ff8749160
Revises: d65e5da4926c
Create Date: 2025-08-01 15:47:26.360700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b53ff8749160'
down_revision = 'd65e5da4926c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('quick_add_settings', sa.JSON(), nullable=True),
    sa.Column('streak_protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('rest_days', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.drop_index('ix_usersettings_user_id', table_name='usersettings')
    op.drop_table('usersettings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('quick_add_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('streak_protection_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rest_days', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('theme_preference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='usersettings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usersettings_pkey')
    )
    op.create_index('ix_usersettings_user_id', 'usersettings', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
