"""add otp table

Revision ID: b73d6dd79e5c
Revises: bd435b6d2e76
Create Date: 2025-09-25 01:16:35.991321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b73d6dd79e5c'
down_revision = 'bd435b6d2e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verification_email'), 'otp_verification', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verification_email'), table_name='otp_verification')
    op.drop_table('otp_verification')
    # ### end Alembic commands ###
