"""add mood before and after; add satisfattion to habit completions

Revision ID: b7f3b488b163
Revises: e422634a9f62
Create Date: 2025-09-18 10:40:42.120102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7f3b488b163'
down_revision = 'e422634a9f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_completion', sa.Column('mood_before', sa.Integer(), nullable=True))
    op.add_column('habit_completion', sa.Column('mood_after', sa.Integer(), nullable=True))
    op.add_column('habit_completion', sa.Column('satisfaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_completion', 'satisfaction')
    op.drop_column('habit_completion', 'mood_after')
    op.drop_column('habit_completion', 'mood_before')
    # ### end Alembic commands ###
