"""habit presets uvsu categories

Revision ID: b84c110acb82
Revises: 93d0fddc3d33
Create Date: 2025-08-22 03:18:48.202108

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b84c110acb82'
down_revision = '93d0fddc3d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CURATED_PRESET', 'COMMUNITY_PRESET', 'EXPERT_PRESET', 'BASIC', name='habituvsucategory').create(op.get_bind())
    op.add_column('habit', sa.Column('uvsu_category', postgresql.ENUM('CURATED_PRESET', 'COMMUNITY_PRESET', 'EXPERT_PRESET', 'BASIC', name='habituvsucategory', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'uvsu_category')
    sa.Enum('CURATED_PRESET', 'COMMUNITY_PRESET', 'EXPERT_PRESET', 'BASIC', name='habituvsucategory').drop(op.get_bind())
    # ### end Alembic commands ###
