"""update goals table

Revision ID: b8dd9f2d3771
Revises: 6fbfd9e5f624
Create Date: 2025-10-26 03:49:15.336613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8dd9f2d3771'
down_revision = '6fbfd9e5f624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
