"""add paused_at, display_order and update status for dreams

Revision ID: b9cbb6f6ea3e
Revises: 5a7aef03395c
Create Date: 2025-11-05 03:09:00.088137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'b9cbb6f6ea3e'
down_revision = '5a7aef03395c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_dream', sa.Column('paused_at', sa.DateTime(), nullable=True))
    op.add_column('user_dream', sa.Column('display_order', sa.Integer(), nullable=True))
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='dreamstatus',
        new_values=['ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED', 'NEXT', 'SOMEDAY'],
        affected_columns=[TableReference(table_schema='public', table_name='user_dream', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema='public',
        enum_name='dreamstatus',
        new_values=['ACTIVE', 'PAUSED', 'ACHIEVED', 'ABANDONED'],
        affected_columns=[TableReference(table_schema='public', table_name='user_dream', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_column('user_dream', 'display_order')
    op.drop_column('user_dream', 'paused_at')
    # ### end Alembic commands ###
