"""notifications updates

Revision ID: bd435b6d2e76
Revises: 2207e00bfa72
Create Date: 2025-09-21 14:32:38.460007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd435b6d2e76'
down_revision = '2207e00bfa72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotificationpreference', sa.Column('discord_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotificationpreference', 'discord_config')
    # ### end Alembic commands ###
