"""add instructions to in depth assessments

Revision ID: bd82c79c610c
Revises: ad522a5c5ba7
Create Date: 2025-10-30 01:25:29.879352

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd82c79c610c'
down_revision = 'ad522a5c5ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessmentquestion', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('indepthassessmentversion', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indepthassessmentversion', 'instructions')
    op.drop_column('assessmentquestion', 'instructions')
    # ### end Alembic commands ###
