"""lifeareas

Revision ID: bea4040ea96d
Revises: f8bfeb8c259a
Create Date: 2025-07-24 18:02:30.213988

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bea4040ea96d'
down_revision = 'f8bfeb8c259a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifearea', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lifearea', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifearea', 'color')
    op.drop_column('lifearea', 'icon')
    # ### end Alembic commands ###
