"""Create scheduled_reminder table

Revision ID: cc9dd806f4b6
Revises: 796257334f7b
Create Date: 2025-10-08 20:51:10.476289

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc9dd806f4b6'
down_revision = '796257334f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reminderpriority').create(op.get_bind())
    sa.Enum('PENDING', 'SENT', 'DELIVERED', 'COMPLETED', 'DISMISSED', 'SNOOZED', 'EXPIRED', 'CANCELLED', name='reminderstatus').create(op.get_bind())
    sa.Enum('HABIT', 'WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'GOAL_DEADLINE', 'GOAL_MILESTONE', 'JOURNAL_PROMPT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', 'USER_CUSTOM', name='remindertype').create(op.get_bind())
    op.create_table('scheduled_reminder',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_type', postgresql.ENUM('HABIT', 'WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'GOAL_DEADLINE', 'GOAL_MILESTONE', 'JOURNAL_PROMPT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', 'USER_CUSTOM', name='remindertype', create_type=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'COMPLETED', 'DISMISSED', 'SNOOZED', 'EXPIRED', 'CANCELLED', name='reminderstatus', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reminderpriority', create_type=False), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('parent_reminder_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['parent_reminder_id'], ['scheduled_reminder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cleanup', 'scheduled_reminder', ['status', 'sent_at'], unique=False, postgresql_where="status IN ('SENT', 'COMPLETED', 'EXPIRED', 'DISMISSED')")
    op.create_index('ix_entity_lookup', 'scheduled_reminder', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_pending_reminders', 'scheduled_reminder', ['reminder_time', 'status'], unique=False, postgresql_where="status = 'PENDING'")
    op.create_index('ix_scheduled_for', 'scheduled_reminder', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_entity_id'), 'scheduled_reminder', ['entity_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_reminder_time'), 'scheduled_reminder', ['reminder_time'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_reminder_type'), 'scheduled_reminder', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_scheduled_for'), 'scheduled_reminder', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_status'), 'scheduled_reminder', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_reminder_user_id'), 'scheduled_reminder', ['user_id'], unique=False)
    op.create_index('ix_user_type_status', 'scheduled_reminder', ['user_id', 'reminder_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_type_status', table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_user_id'), table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_status'), table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_scheduled_for'), table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_reminder_type'), table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_reminder_time'), table_name='scheduled_reminder')
    op.drop_index(op.f('ix_scheduled_reminder_entity_id'), table_name='scheduled_reminder')
    op.drop_index('ix_scheduled_for', table_name='scheduled_reminder')
    op.drop_index('ix_pending_reminders', table_name='scheduled_reminder', postgresql_where="status = 'PENDING'")
    op.drop_index('ix_entity_lookup', table_name='scheduled_reminder')
    op.drop_index('ix_cleanup', table_name='scheduled_reminder', postgresql_where="status IN ('SENT', 'COMPLETED', 'EXPIRED', 'DISMISSED')")
    op.drop_table('scheduled_reminder')
    sa.Enum('HABIT', 'WHEEL_OF_LIFE', 'VALUES_ASSESSMENT', 'GOAL_DEADLINE', 'GOAL_MILESTONE', 'JOURNAL_PROMPT', 'WEEKLY_REVIEW', 'MONTHLY_REFLECTION', 'QUARTERLY_CHECK_IN', 'ANNUAL_PLANNING', 'USER_CUSTOM', name='remindertype').drop(op.get_bind())
    sa.Enum('PENDING', 'SENT', 'DELIVERED', 'COMPLETED', 'DISMISSED', 'SNOOZED', 'EXPIRED', 'CANCELLED', name='reminderstatus').drop(op.get_bind())
    sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reminderpriority').drop(op.get_bind())
    # ### end Alembic commands ###
