"""add due_date to habits

Revision ID: d29eb07f778f
Revises: 07f471bb6637
Create Date: 2025-10-23 12:13:33.159279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd29eb07f778f'
down_revision = '07f471bb6637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_habit_due_date'), 'habit', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_due_date'), table_name='habit')
    op.drop_column('habit', 'due_date')
    # ### end Alembic commands ###
