"""update trackables table

Revision ID: d2e40a2cb0c6
Revises: b8dd9f2d3771
Create Date: 2025-10-26 20:07:47.014386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2e40a2cb0c6'
down_revision = 'b8dd9f2d3771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NONE', 'KG', 'LBS', 'STEPS', 'COUNT', 'PERCENT', 'RATING', 'HOURS', 'MINUTES', 'SECONDS', name='trackableunit').create(op.get_bind())
    sa.Enum('NUMERIC', 'SCALE', 'BOOLEAN', 'DURATION', 'MULTIPLE_CHOICE', name='trackabletype').create(op.get_bind())
    op.create_table('trackable_group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackable_entries',
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trackable_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackableoption',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trackable_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry')
    op.add_column('trackable', sa.Column('type', postgresql.ENUM('NUMERIC', 'SCALE', 'BOOLEAN', 'DURATION', 'MULTIPLE_CHOICE', name='trackabletype', create_type=False), nullable=False))
    op.add_column('trackable', sa.Column('unit', postgresql.ENUM('NONE', 'KG', 'LBS', 'STEPS', 'COUNT', 'PERCENT', 'RATING', 'HOURS', 'MINUTES', 'SECONDS', name='trackableunit', create_type=False), nullable=False))
    op.add_column('trackable', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('trackable', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('trackable', sa.Column('goal', sa.Float(), nullable=True))
    op.add_column('trackable', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('trackable', sa.Column('is_calculated', sa.Boolean(), nullable=False))
    op.add_column('trackable', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.alter_column('trackable', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'trackable', 'trackable_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackable', type_='foreignkey')
    op.alter_column('trackable', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('trackable', 'group_id')
    op.drop_column('trackable', 'is_calculated')
    op.drop_column('trackable', 'is_active')
    op.drop_column('trackable', 'goal')
    op.drop_column('trackable', 'icon')
    op.drop_column('trackable', 'color')
    op.drop_column('trackable', 'unit')
    op.drop_column('trackable', 'type')
    op.create_table('entry',
    sa.Column('value_numeric', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('value_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('value_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('value_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('entry_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trackable_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], name='entry_trackable_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entry_pkey')
    )
    op.drop_table('trackableoption')
    op.drop_table('trackable_entries')
    op.drop_table('trackable_group')
    sa.Enum('NUMERIC', 'SCALE', 'BOOLEAN', 'DURATION', 'MULTIPLE_CHOICE', name='trackabletype').drop(op.get_bind())
    sa.Enum('NONE', 'KG', 'LBS', 'STEPS', 'COUNT', 'PERCENT', 'RATING', 'HOURS', 'MINUTES', 'SECONDS', name='trackableunit').drop(op.get_bind())
    # ### end Alembic commands ###
