"""default quite hours to none

Revision ID: d4f21a123d4a
Revises: a33239682eb9
Create Date: 2025-09-25 21:17:09.171676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4f21a123d4a'
down_revision = 'a33239682eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usernotificationpreference', 'quiet_hours_start',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usernotificationpreference', 'quiet_hours_end',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usernotificationpreference', 'quiet_hours_end',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usernotificationpreference', 'quiet_hours_start',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
