"""username and journey_name

Revision ID: d65e5da4926c
Revises: b4cf87a2a016
Create Date: 2025-07-31 14:22:17.073303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd65e5da4926c'
down_revision = 'b4cf87a2a016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('journey_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'journey_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
