"""remove tables

Revision ID: e802264fd31b
Revises: ffe9c6344745
Create Date: 2025-11-14 03:10:13.018072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e802264fd31b'
down_revision = 'ffe9c6344745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
