"""Initial migration

Revision ID: f8bfeb8c259a
Revises:
Create Date: 2025-07-23 04:42:54.894258

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8bfeb8c259a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='statusenum').create(op.get_bind())
    sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'NONE', name='recurringruleenum').create(op.get_bind())
    sa.Enum('BIRTHDAY', 'TRIP', 'MEETING', 'BIG_DAY', 'NONE', name='eventtypeenum').create(op.get_bind())
    sa.Enum('HAPPY', 'SAD', 'ANGRY', 'ANXIOUS', 'EXCITED', 'CALM', 'BORED', 'GRATEFUL', 'TIRED', 'MOTIVATED', 'STRESSED', 'LONELY', 'CONFIDENT', 'CURIOUS', name='moodenum').create(op.get_bind())
    sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='frequencyenum').create(op.get_bind())
    sa.Enum('BOOK', 'VIDEO', 'STUDY', 'RESEARCH_PAPER', name='resourcetypeenum').create(op.get_bind())
    sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'custom', name='proficiencylevelenum').create(op.get_bind())
    sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus').create(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='goalpriority').create(op.get_bind())
    sa.Enum('HEALTH', 'CAREER', 'FINANCES', 'RELATIONSHIPS', 'PERSONAL_GROWTH', 'SPIRITUALITY', 'FUN_RECREATION', 'ENVIRONMENT', 'OTHER', name='goalcategory').create(op.get_bind())
    sa.Enum('FRIENDS', 'RELATIONSHIPS', 'LOVE', 'MONEY', 'SPIRITUALITY', 'FUN', 'CAREER', 'HEALTH', 'FAMILY', 'GROWTH', 'FINANCE', name='lifeareasenum').create(op.get_bind())
    op.create_table('avatar',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifearea',
    sa.Column('name', postgresql.ENUM('FRIENDS', 'RELATIONSHIPS', 'LOVE', 'MONEY', 'SPIRITUALITY', 'FUN', 'CAREER', 'HEALTH', 'FAMILY', 'GROWTH', 'FINANCE', name='lifeareasenum', create_type=False), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifearea_name'), 'lifearea', ['name'], unique=True)
    op.create_table('preference',
    sa.Column('metric_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_dark_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_view', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_goal_priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_notification_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_sound', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('show_tutorials', sa.Boolean(), nullable=False),
    sa.Column('shortcut_keys_enabled', sa.Boolean(), nullable=False),
    sa.Column('voice_assistant', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', postgresql.ENUM('BOOK', 'VIDEO', 'STUDY', 'RESEARCH_PAPER', name='resourcetypeenum', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routinetype',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proficiency_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', 'expert', 'custom', name='proficiencylevelenum', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes_and_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lifearea_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conceptresourcelink',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('concept_id', 'resource_id')
    )
    op.create_table('skilllifearealink',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('lifearea_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'lifearea_id')
    )
    op.create_table('skillresourcelink',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'resource_id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_id', sa.Uuid(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('total_habits_completed', sa.Integer(), nullable=False),
    sa.Column('self_mastery_score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_self_mastery_score'), 'user', ['self_mastery_score'], unique=False)
    op.create_index(op.f('ix_user_total_habits_completed'), 'user', ['total_habits_completed'], unique=False)
    op.create_table('assessmentquestion',
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessmentresult',
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('notes_and_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('BIRTHDAY', 'TRIP', 'MEETING', 'BIG_DAY', 'NONE', name='eventtypeenum', create_type=False), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('recurring_rule', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'NONE', name='recurringruleenum', create_type=False), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reminder_time', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED', name='statusenum', create_type=False), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reflection', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mood', postgresql.ENUM('HAPPY', 'SAD', 'ANGRY', 'ANXIOUS', 'EXCITED', 'CALM', 'BORED', 'GRATEFUL', 'TIRED', 'MOTIVATED', 'STRESSED', 'LONELY', 'CONFIDENT', 'CURIOUS', name='moodenum', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('category', postgresql.ENUM('HEALTH', 'CAREER', 'FINANCES', 'RELATIONSHIPS', 'PERSONAL_GROWTH', 'SPIRITUALITY', 'FUN_RECREATION', 'ENVIRONMENT', 'OTHER', name='goalcategory', create_type=False), nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='goalpriority', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('S', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('M', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('A', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('R', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('T', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lifearea_id', sa.Uuid(), nullable=True),
    sa.Column('parent_goal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identitystatement',
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mood', postgresql.ENUM('HAPPY', 'SAD', 'ANGRY', 'ANXIOUS', 'EXCITED', 'CALM', 'BORED', 'GRATEFUL', 'TIRED', 'MOTIVATED', 'STRESSED', 'LONELY', 'CONFIDENT', 'CURIOUS', name='moodenum', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('item_data', sa.JSON(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('repeat_frequency', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='frequencyenum', create_type=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['routinetype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skillprogress',
    sa.Column('activity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackable',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('lifearea_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersettings',
    sa.Column('quick_add_settings', sa.JSON(), nullable=True),
    sa.Column('streak_protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('rest_days', sa.JSON(), nullable=True),
    sa.Column('theme_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersettings_user_id'), 'usersettings', ['user_id'], unique=True)
    op.create_table('wheeloflife',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('value_time', sa.DateTime(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(), nullable=True),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trackable_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventtaglink',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', 'user_id')
    )
    op.create_table('goal_milestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestone_goal_completed', 'goal_milestone', ['goal_id', 'is_completed'], unique=False)
    op.create_index('idx_milestone_target_date', 'goal_milestone', ['target_date'], unique=False)
    op.create_index(op.f('ix_goal_milestone_goal_id'), 'goal_milestone', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_milestone_is_completed'), 'goal_milestone', ['is_completed'], unique=False)
    op.create_table('habit',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('isElastic', sa.Boolean(), nullable=False),
    sa.Column('is_keystone', sa.Boolean(), nullable=False),
    sa.Column('cue', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_the_one_thing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('habitType', sa.String(), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=True),
    sa.Column('timers', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.JSON(), nullable=True),
    sa.Column('reminders', sa.JSON(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('preset_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('primary_life_area_id', sa.Uuid(), nullable=True),
    sa.Column('identity_id', sa.Uuid(), nullable=True),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('source_preset_id', sa.Uuid(), nullable=True),
    sa.Column('stack_with_habit_id', sa.Uuid(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('totalSkips', sa.Integer(), nullable=False),
    sa.Column('lastCompletedLevel', sa.String(), nullable=True),
    sa.Column('redoCount', sa.JSON(), nullable=True),
    sa.Column('totalCompletions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hasFlexibility', sa.Boolean(), nullable=False),
    sa.Column('lastCompletionDate', sa.DateTime(), nullable=True),
    sa.Column('reminderTime', sa.Time(), nullable=True),
    sa.Column('reminderDays', sa.JSON(), nullable=True),
    sa.Column('lastRedoLevel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lastSkipReason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lastSkipSolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identitystatement.id'], ),
    sa.ForeignKeyConstraint(['primary_life_area_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['source_preset_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['stack_with_habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_is_preset'), 'habit', ['is_preset'], unique=False)
    op.create_table('journaltaglink',
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('journal_id', 'tag_id', 'user_id')
    )
    op.create_table('routinetasklink',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'routine_id')
    )
    op.create_table('skillgoallink',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'goal_id', 'user_id')
    )
    op.create_table('trackabletaglink',
    sa.Column('trackable_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('trackable_id', 'tag_id', 'user_id')
    )
    op.create_table('usertasklink',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('wheeloflifelifearealink',
    sa.Column('wheeloflife_id', sa.Uuid(), nullable=False),
    sa.Column('lifearea_id', sa.Uuid(), nullable=False),
    sa.Column('lifeArea_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.ForeignKeyConstraint(['wheeloflife_id'], ['wheeloflife.id'], ),
    sa.PrimaryKeyConstraint('wheeloflife_id', 'lifearea_id')
    )
    op.create_table('habit_completion',
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('level_completed', sa.String(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_skip', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('skip_solution', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('redo_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'habit_id', 'completion_date', name='uq_user_habit_date')
    )
    op.create_index(op.f('ix_habit_completion_completion_date'), 'habit_completion', ['completion_date'], unique=False)
    op.create_index(op.f('ix_habit_completion_habit_id'), 'habit_completion', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_completion_is_skip'), 'habit_completion', ['is_skip'], unique=False)
    op.create_index(op.f('ix_habit_completion_user_id'), 'habit_completion', ['user_id'], unique=False)
    op.create_index('ix_user_date', 'habit_completion', ['user_id', 'completion_date'], unique=False)
    op.create_index('ix_user_habit', 'habit_completion', ['user_id', 'habit_id'], unique=False)
    op.create_table('habitlifearealink',
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('lifearea_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['lifearea_id'], ['lifearea.id'], ),
    sa.PrimaryKeyConstraint('habit_id', 'lifearea_id')
    )
    op.create_table('habitresourcelink',
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('habit_id', 'resource_id')
    )
    op.create_table('routinehabitlink',
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('advanceNotice', sa.Integer(), nullable=True),
    sa.Column('customDays', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('habit_id', 'routine_id')
    )
    op.create_table('userhabitlink',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('habit_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'habit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userhabitlink')
    op.drop_table('routinehabitlink')
    op.drop_table('habitresourcelink')
    op.drop_table('habitlifearealink')
    op.drop_index('ix_user_habit', table_name='habit_completion')
    op.drop_index('ix_user_date', table_name='habit_completion')
    op.drop_index(op.f('ix_habit_completion_user_id'), table_name='habit_completion')
    op.drop_index(op.f('ix_habit_completion_is_skip'), table_name='habit_completion')
    op.drop_index(op.f('ix_habit_completion_habit_id'), table_name='habit_completion')
    op.drop_index(op.f('ix_habit_completion_completion_date'), table_name='habit_completion')
    op.drop_table('habit_completion')
    op.drop_table('wheeloflifelifearealink')
    op.drop_table('usertasklink')
    op.drop_table('trackabletaglink')
    op.drop_table('skillgoallink')
    op.drop_table('routinetasklink')
    op.drop_table('journaltaglink')
    op.drop_index(op.f('ix_habit_is_preset'), table_name='habit')
    op.drop_table('habit')
    op.drop_index(op.f('ix_goal_milestone_is_completed'), table_name='goal_milestone')
    op.drop_index(op.f('ix_goal_milestone_goal_id'), table_name='goal_milestone')
    op.drop_index('idx_milestone_target_date', table_name='goal_milestone')
    op.drop_index('idx_milestone_goal_completed', table_name='goal_milestone')
    op.drop_table('goal_milestone')
    op.drop_table('eventtaglink')
    op.drop_table('entry')
    op.drop_table('wheeloflife')
    op.drop_index(op.f('ix_usersettings_user_id'), table_name='usersettings')
    op.drop_table('usersettings')
    op.drop_table('trackable')
    op.drop_table('task')
    op.drop_table('skillprogress')
    op.drop_table('routine')
    op.drop_table('reminder')
    op.drop_table('refresh_tokens')
    op.drop_table('log')
    op.drop_table('journal')
    op.drop_table('item')
    op.drop_table('insight')
    op.drop_table('identitystatement')
    op.drop_table('goal')
    op.drop_table('event')
    op.drop_table('assessmentresult')
    op.drop_table('assessmentquestion')
    op.drop_index(op.f('ix_user_total_habits_completed'), table_name='user')
    op.drop_index(op.f('ix_user_self_mastery_score'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('skillresourcelink')
    op.drop_table('skilllifearealink')
    op.drop_table('conceptresourcelink')
    op.drop_table('assessment')
    op.drop_table('tag')
    op.drop_table('skill')
    op.drop_table('routinetype')
    op.drop_table('resource')
    op.drop_table('preference')
    op.drop_index(op.f('ix_lifearea_name'), table_name='lifearea')
    op.drop_table('lifearea')
    op.drop_table('concept')
    op.drop_table('avatar')
    sa.Enum('FRIENDS', 'RELATIONSHIPS', 'LOVE', 'MONEY', 'SPIRITUALITY', 'FUN', 'CAREER', 'HEALTH', 'FAMILY', 'GROWTH', 'FINANCE', name='lifeareasenum').drop(op.get_bind())
    sa.Enum('HEALTH', 'CAREER', 'FINANCES', 'RELATIONSHIPS', 'PERSONAL_GROWTH', 'SPIRITUALITY', 'FUN_RECREATION', 'ENVIRONMENT', 'OTHER', name='goalcategory').drop(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='goalpriority').drop(op.get_bind())
    sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus').drop(op.get_bind())
    sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'custom', name='proficiencylevelenum').drop(op.get_bind())
    sa.Enum('BOOK', 'VIDEO', 'STUDY', 'RESEARCH_PAPER', name='resourcetypeenum').drop(op.get_bind())
    sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='frequencyenum').drop(op.get_bind())
    sa.Enum('HAPPY', 'SAD', 'ANGRY', 'ANXIOUS', 'EXCITED', 'CALM', 'BORED', 'GRATEFUL', 'TIRED', 'MOTIVATED', 'STRESSED', 'LONELY', 'CONFIDENT', 'CURIOUS', name='moodenum').drop(op.get_bind())
    sa.Enum('BIRTHDAY', 'TRIP', 'MEETING', 'BIG_DAY', 'NONE', name='eventtypeenum').drop(op.get_bind())
    sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'NONE', name='recurringruleenum').drop(op.get_bind())
    sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='statusenum').drop(op.get_bind())
    # ### end Alembic commands ###
