"""updata mindfulness tables

Revision ID: ffe9c6344745
Revises: 024bc6b31dae
Create Date: 2025-11-13 00:44:26.158118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffe9c6344745'
down_revision = '024bc6b31dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_completions',
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('breathing_pattern_used', postgresql.ENUM('BOX_4_4_4_4', 'RELAX_4_7_8', 'EQUAL_5_5', 'BALANCED_4_4', 'ENERGIZE_2_1', 'CUSTOM', 'WIM_HOF', name='breathingpatterntype', create_type=False), nullable=True),
    sa.Column('custom_breathing_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['mindfulness_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_completions_exercise_id'), 'exercise_completions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_completions_user_id'), 'exercise_completions', ['user_id'], unique=False)
    op.create_table('user_exercise_tracking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('times_completed', sa.Integer(), nullable=False),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('preferred_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['mindfulness_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='unique_user_exercise')
    )
    op.create_index(op.f('ix_user_exercise_tracking_exercise_id'), 'user_exercise_tracking', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_tracking_user_id'), 'user_exercise_tracking', ['user_id'], unique=False)
    op.alter_column('mindfulness_exercises', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('mindfulness_exercises', 'last_completed')
    op.drop_column('mindfulness_exercises', 'favorited')
    op.drop_column('mindfulness_exercises', 'times_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mindfulness_exercises', sa.Column('times_completed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mindfulness_exercises', sa.Column('favorited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mindfulness_exercises', sa.Column('last_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('mindfulness_exercises', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_user_exercise_tracking_user_id'), table_name='user_exercise_tracking')
    op.drop_index(op.f('ix_user_exercise_tracking_exercise_id'), table_name='user_exercise_tracking')
    op.drop_table('user_exercise_tracking')
    op.drop_index(op.f('ix_exercise_completions_user_id'), table_name='exercise_completions')
    op.drop_index(op.f('ix_exercise_completions_exercise_id'), table_name='exercise_completions')
    op.drop_table('exercise_completions')
    # ### end Alembic commands ###
